### ISSUE TITLE
Matrix representation of item batteries does not work in instruments

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#12]
In den aus den csv-Dateien generierten Instrumenten ist die Darstellung von Fragematrizen (1 Hauptfrage, dann x Statements mit identischer Antwortskala) noch nicht so wie angedacht. S. z.B. inv0100 bis inv0111 in Modul3_Basismodul - sollte eine große Matrix sein. Ist unsere Bereitstellung in questions.csv, answers.csv und logical_variables.csv hier noch verkehrt oder ist der Fehler woanders?

**Comment by mhebing** [comment]
Sollte auf Eurer Seite alles passen, ich werde die Woche das Layout anpassen.

**Comment by kkrell** [comment]
Die Darstellung ist noch nicht so. Es sind immer noch Einzelfragen pro Item in einer Itembatterie - da steht der Fragetext dann auch nur in der Frage zum ersten Item dabei (komischerweise hier in Matrizenform). Wie gesagt, meld dich, wenn wir dir das für die korrekte Darstellung irgendwie anders liefern müssen.

**Comment by mhebing** [comment]
Dieses mal liegt es wohl doch an den Metadaten. Wenn Ihr wollt, dass etwas auf einer Seite erscheinen soll, müsste bitte jeweils der Eintrag in der Spalte "question" übereinstimmen:

Momentan, falsch:

| question | item |
| --- | --- |
| inv0100 |  |
| inv0100 | 1 |
| inv0101 | 2 |
| inv0102 | 3 |
| inv0103 | 4 |

So würde es hingegen funktionieren:

| question | item |
| --- | --- |
| inv0100 |  |
| inv0100 | 1 |
| inv0100 | 2 |
| inv0100 | 3 |
| inv0100 | 4 |

**Comment by kkrell** [comment]
Oh ja danke, genau das isses! Wird korrigiert!
Noch eine Frage: Ist es auch richtig so, dass aus dem Instrument (Matrixdarstellung) nicht ersichtlich wird, wie die Variablennamen der einzelnen Issues der Matrix im Datensatz sind?

**Comment by mhebing** [comment]
Damit es da jetzt auch für alle Studien schnell vorangeht, hab ich erst mal nur den pragmatischen Ansatz implementiert, dass eine ganze Frage (mit allen Items) zu den entsprechenden Variablen verlinkt wird.

Grundsätzlich können wir aber auch noch präziser werden und bei jedem Item die entsprechende(n) Variablen verlinken. Fürs erste bin ich aber davon ausgegangen, dass das aus den jeweiligen Labels der Variablen ausreichend ersichtlich ist – oder nicht?

**Comment by kkrell** [comment]
Danke für die Erläuterung! Ja, ich denke es wird grundsätzlich auch aus den Variablenlabels bzw. der Variablenbenennung ersichtlich.
