### ISSUE TITLE
Keyword and variable search within study does not work

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#13]
Suche nach Stichworten sowie Variablennamen ergibt Buchstabensalatmischung aus Fragen (aus Instrumenten) und Variablen (wobei z.B. für emp0600 nur die Mode-Variable emp0600_r ausgegeben wird). 
Suche nach Stichwort innerhalb von Studie („namespace:'twinlife' occupational status“) gibt auch Ergebnisse aus anderen Studien (SOEP, Pairfam) aus

**Comment by kkrell** [comment]
Nach dem Update kommt beim Suchen kein Buchstabensalat und keine Ergebnisse aus anderen Studien mehr, aber die Suche nach Stichworten (Beispiel "risk") führt zu keinen sinnvollen Ergebnissen - nur eine Auswahl von den 5300 Ergebnissen erscheint, wobei sich mir erstmal kein Bezug zu "risk" erschließt.
... Wenn man allerdings eine Variable aus der Ergebnisliste anklickt, funktioniert wiederum die Darstellung der Statistiken, Häufigkeiten usw.

**Comment by kkrell** [comment]
**Innerhalb** der Instrumente und Datensätze funktioniert die Suche jetzt prima. Wenn ich allerdings beispielsweise auf der Startseite von TwinLife in das obere Suchfeld ("+namespace:'twinlife'") etwas eingebe, kommen nicht nur zum Suchbegriff Ergebnisse, sondern auch zu anderen Variablen und Fragen (unsortiert). Hier scheint die Suche noch nicht ganz so gut zu funktionieren.

**Comment by mhebing** [comment]
Auch hier danke für den Hinweis. Caro sitzt gerade daran, das Suchinterface zu überarbeiten. Darauf würde ich jetzt gerne erst mal warten. (Sollte Anfang des Jahres online gehen…)

**Comment by kkrell** [comment]
Nach wie vor gilt: Innerhalb der Datensätze und Fragebögen funktioniert die Suche nach Stichworten und Variablennamen super. Aber: Wie funktioniert das Suchfeld auf der Startseite? Egal was ich da eingebe, es kommen keine Ergebnisse. Muss man da was beachten, noch zusätzlich eingeben oder so, um z.B. gleichzeitig in Fragebögen UND Datensätzen nach Stichworten zu suchen?

**Comment by afuetterer** [comment]
Danke fürs Bescheid geben.
Es gab einen Fehler beim Indexieren.

Kannst du nochmal unter https://ddionrails.soep.de/twinlife etwas suchen bzw unter https://ddionrails.soep.de/search/ ?
Zum Beispiel "job", das sollte sowohl "questions" als auch "variables" als Resultate ergeben.

**Comment by kkrell** [comment]
Die Suche auf der Startseite von TwinLife sowie die studienübergreifende Suche scheinen jetzt zu funktionieren, es tauchen Fragen und Variablen auf.
Ich wundere mich nur, dass einige Fragen teils mehrfach auftauchen, die demselben Fragebogen entstammen. Beispiel edu0100: Die Frage kommt in drei Fragebögen vor, zu jedem Fragebogen gibt es zwei Treffer... Oder sehe ich da einen Unterschied nicht?

Wenn man unter "Instruments" eine Variable sucht, kommen keine Treffer. Ich vermute, weil dort nur nach Instrumenten selbst und nicht nach Variablen IN Instrumenten gesucht wird. Könnte mir aber vorstellen, dass Nutzer auch dort versuchen, die Frage zu einer Variable zu suchen.

**Comment by afuetterer** [comment]
Es gibt gerade eine Inkosistenz zwischen Datenbank und Suchmaschine. Die doppelten Suchergebnisse bitte ich vorerst zu ignorieren. Das wird behoben und auf dem Live-Server paneldata.org nicht geschehen.

Abgesehen davon: Was meinst du mit der Suche unter "Instruments"?

Meinst du die untere Tabelle auf diesem Screenshot?
![t](https://user-images.githubusercontent.com/35225576/58169438-05bec000-7c91-11e9-8658-6d2f7f880b93.png)
Das ist zum Filtern der Instrumente in dieser Tabelle, richtig. Eine Suche nach Variablen ist dort nicht möglich.

Kann ich das Issue schließen?

**Comment by kkrell** [comment]
Ja genau, das meinte ich. Danke für die Rückmeldung!
