### ISSUE TITLE
Placeholder symbol in questions in instruments?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#14]
Einige Fragen (z.B. spa0401), die Platzhalter (im Text meist "...") enthalten, haben in der Darstellung ein Symbol. Ist das so gewollt?

**Comment by mhebing** [comment]
Oh, dann haben wir wohl doch ein Problem mit dem Encoding.

Drei Punkte (wenn nicht als drei einzelne Punkte geschrieben), sind ein Sonderzeichen (ähnlich wie "ä", "ö" und "ü"):

```
Drei einzelne Punkte:  ...
Als ein Zeichen:       …
```

Würde ich bei Gelegenheit mal mit Suchen und Ersetzen lösen. Ist Dir dabei noch ein anderer Fall außer den drei Punkten aufgefallen?

**Comment by kkrell** [comment]
Alles klar, das leuchtet ein! Habs schon in der ursprünglichen Metadatentabelle korrigiert, sollte also beim nächsten Update der csv-Dateien kein Problem mehr sein. Weitere Fälle sind mir bisher nicht aufgefallen.
