### ISSUE TITLE
No "label" and "description" column in questionnaires.csv?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#17]
Die "instruments" Seite auf paneldata.org sieht aus, als sollte dort ein Label und vielleicht eine Beschreibung zu jedem Datensatz rein. Die questionnaires.csv-Datei hat aber noch keine entsprechenden Spalten. Kann/soll ich die einfach einfügen oder ist keine kurze Fragebogenbeschreibung vorgesehen?

**Comment by mhebing** [comment]
Die `questionnaires.csv` darf auch label und description haben. Wenn die bei Euch in der CSV noch fehlt, gerne einfach hinzufügen.

**Comment by kkrell** [comment]
Done
