### ISSUE TITLE
Filter conditions missing in instruments

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#18]
In der alten Version von paneldata.org standen unsere Filterbedingungen so schön unter den Fragen in den Fragebögen. Kann man das hier vielleicht auch wieder einstellen, dass die mit dokumentiert werden?
Die "filter" Spalte mit der Info steht in questions.csv. Kommt dort auch die Spalte "description" rein, die wir mit Zusatzinfos/Quellen gefüllt haben und die in den Instrumenten auftauchen soll?

**Comment by kkrell** [comment]
Die Filterconditions sind jetzt da, danke :)
Ich find allerdings immer noch nicht die "description" Infos, weder im Fragebogen, noch bei den Variablen!

**Comment by mhebing** [comment]
Danke für den Hinweis mit den description Feld! Schaue ich mir an.

**Comment by kkrell** [comment]
Die Filterbedingungen, die in questions.csv abgelegt wurden, werden nun nicht mehr bei den Fragebögen angezeigt. Kann das noch geändert werden?
Und auch die descriptions (in questions.csv abgelegt), die unsere Quellen beinhalten, werden nach wie vor weder im Fragebogen, noch bei der Variable dargestellt, wenn ich es richtig sehe. Können die irgendwo angezeigt werden?

**Comment by afuetterer** [comment]
Hast du bitte zu den drei Bereichen je ein Beispiel?
- Filterbedingungen in questions.csv
- Descriptions in questions.csv
- Was ist das dritte? Descriptions von Variablen?

Ich sehe bspw. hier etwas, das nach Filterbedingung aussieht:
https://ddionrails.soep.de/twinlife/inst/twinlife-2014-f2f_alteri-fragebogen/fam0200
Meinst du so etwas?

**Comment by kkrell** [comment]
Das mit den Filtern hat sich erledigt, da hatte ich mich verguckt. Das funktioniert wie es soll. Sorry!

Was die descriptions betrifft: Wir haben unsere Quellen in der Spalte descriptions in questions.csv abgelegt. Es wäre toll, wenn die entweder bei der Variable oder im Fragebogen angezeigt würden, bestenfalls sogar an beiden Stellen. Auf paneldata gibt es bei der Variable tatsächlich das Feld "description", aber dieses ist leer und nicht mit unseren Quellen befüllt ... 
Beispiel: aas0100u. Diese Variable enthält in questions.csv in der Spalte descriptions die Angabe "Adapted from: Panel analysis of intimate relationships and family dynamics (pairfam): Pairfam Codebook Child Wave 7 2014/2015." Diese taucht jedoch nirgends in paneldata auf.

Beantwortet das deine Fragen?

**Comment by afuetterer** [comment]
Okay, verstehe.
Ich öffne ein neues Issue, wenn die Angelegenheit "Filter conditions missing in instruments" sich erledigt hat.
