### ISSUE TITLE
Problems after Server Update - dataset labels still missing

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#19]
Hallo Marcel,
vielen Dank für das Server Update - da hat sich doch einiges getan! Ich bin allerdings an einigen Stellen auch etwas verwirrt und ´dachte, ich erstelle dafür am besten erstmal wieder Issues:

Bei den Datasets sind immer noch keine Labels sichtbar, aber die hatte ich doch schon in datasets.csv eingetragen und an dich gepusht?!

**Comment by mhebing** [comment]
Sollte jetzt passen:

https://data.soep.de/twinlife#datasets

Das war echt der schlimmste Bug ever...
