### ISSUE TITLE
Variable content and statistics missing

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#21]
Irgendwie scheint es die Darstellung der Variablen bei diesem Update zerschossen zu haben (Wenn man über Datasets geht und auf die Variablen klickt - in den Instruments geht es). Wenn ich eine Variable anklicke, kommt jedenfalls gar nichts mehr, außer dem Label; keine Statistiken und Kategorien, Häufigkeiten usw.

**Comment by mhebing** [comment]
@kkrell Könntest Du bitte noch mal schauen, ob das jetzt passt und ggf. den Issue zumachen?

**Comment by kkrell** [comment]
Das sieht super aus, danke!
