### ISSUE TITLE
Link dataset<->instrument not working

### ISSUE THREAD

**Issue by volkerlang** [paneldata/twinlife#23]
Hallo Marcel,

auf paneldata.org bzw. data.soep.de funktioniert die Verlinkung von Datensätzen und Fragebögen für TwinLife nicht. Evtl. ja nach dem Update ..

Falls mit der von uns gelieferten logicalvariables.csv was nicht stimmt oder wir anders Helfen können, 
dann gib uns bitte Bescheid.

Die Daten sind seit 04.11. bei GESIS released, daher wäre es für die Nutzer gut, wenn die Verlinkung funktionieren würde.

Danke und LG, 
Volker

**Comment by mhebing** [comment]
Alles klar, schaue ich mir an. Generelle bitte: wenn Du mir so einen Fehler meldest, könntest Du mir bitte immer einen Link / Beispiel mit reinkopieren, wo es nicht funktioniert, aber funktionieren sollte… Vielen Dank!

**Comment by kkrell** [comment]
Nach erneutem Update funktioniert der Link zwischen Variable und Instrument(en) nicht mehr. Issue wieder öffnen?

**Comment by volkerlang** [comment]
Ich glaube mich zu erinnern, dass das damals auf dem Testserver auch so war, auf dem paneldata-Server dann aber nicht. Wäre klar besser, wenn das auch auf dem Testserver funktioniert - aber evtl. hilft das ja bei der Fehlersuche ..

Viele Grüße,
Volker

**Comment by afuetterer** [comment]
Ist erledigt.
