### ISSUE TITLE
Insruments / questionnaires in one document?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#24]
Ist es geplant, dass man für den/die Fragebögen ein Dokument erstellen kann? Also dass man sagen kann "zeige mir für Modul 3 den kompletten Fragebogen" und dann erscheint der in HTML oder PDF? Oder bleibt es dabei, dass das Instrument als Liste von Variablen dokumentiert wird, die man einzeln anklicken kann?

**Comment by mhebing** [comment]
In DDI on Rails alles auf einer Seite darzustellen dürfte den Server in die Knie zwingen.

Aber es ist geplant, dass PDFs zu den Fragebögen angeboten werden. (Steht auch schon recht weit oben auf der Feature-Liste.)

Wenn Ihr aus den Metadaten (den CSV Dateien) ein PDF erzeugen wollt, kann Knut euch helfen. Er hat ein entsprechendes Programm in R vorbereitet.

**Comment by kkrell** [comment]
Alles klar, prima!
