### ISSUE TITLE
What do we use for the study identifier

### ISSUE THREAD

**Issue by mhebing** [paneldata/twinlife#27]
@kkrell @volkerlang Welchen Identifier wollen wir für die Studie verwenden?

twinlife vs. twinlife-panel – Meine Präferenz wäre inzwischen nur noch "twinlife" zu nehmen.

(Das ist auch der Grund, warum gerade die Links zwischen Variablen und Fragen nicht funktionieren…)

**Comment by volkerlang** [comment]
Hallo Marcel,

ja, das wäre auch unsere Präferenz, denke ich, also nur "twinlife".
Ich lade dann nochmal entsprechend upgedatete csv's hoch.
Voll gut das Du den Fehler gefunden hast! Danke!

LG Volker

**Comment by mhebing** [comment]
:+1:
