### ISSUE TITLE
questions.csv: no answer_list if scale != cat

### ISSUE THREAD

**Issue by mhebing** [paneldata/twinlife#28]
@kkrell @volkerlang Noch ein zweites Problem:

Wenn in der questions.csv eine Matrixfrage beginnt, ist das erste Element ja scale == "txt". Danach kommen die "cat" Elemente mit den Verweisen zur answer_list.

Das "txt" Element darf bitte keinen Eintrag in der answer_list Spalte haben, sonst zieht das Layout das Element mit in die Matrix. Sorry!

**Comment by volkerlang** [comment]
Alles klar, ich kümmer mich drum, kann ein paar Minuten dauern!

LG Volker

**Comment by volkerlang** [comment]
Hallo Marcel,

hab an allen Stellen "twinlife-panel" durch "twinlife" ersetzt und in der questions.csv answer_list = "" wenn es sich um die erste Zeile einer Matrixfrage handelt. Müsste jetzt hoffentlich beides passen! :-)

Danke fürs updaten und LG,
Volker
