### ISSUE TITLE
Order of Numbers

### ISSUE THREAD

**Issue by volkerlang** [paneldata/twinlife#31]
Bei einigen Fragen stimmt die Antwortreihenfolge nicht
(und auch die Missingrange - aber das ist nach dem Update wahrscheinlich weg, denk ich)
Beispiel:
![reihenfolgezahlen](https://cloud.githubusercontent.com/assets/15111430/20842487/fd2b656e-b8b7-11e6-829e-f0f2f6bfbfe7.JPG)

**Comment by mhebing** [comment]
Das mit der Reihenfolge in den variable categories ist leider ein ganz dummer Bug in R. Wir schauen, dass wir das komplett in Python übertragen, dauert leider noch ein klein wenig.

**Comment by volkerlang** [comment]
Alles klar, danke für die Info!

**Comment by kkrell** [comment]
Das Problem scheint nicht mehr zu bestehen, Issue kann geschlossen werden.

**Comment by kkrell** [comment]
Bei edu0203 (Arbeitsstunden) wird die Reihenfolge nicht korrekt angezeigt (evtl. nicht erst seit erneutem Update). Zahlen mit Nachkommastellen werden nicht korrekt einsortiert. Issue wieder öffnen?

**Comment by afuetterer** [comment]
https://ddionrails.soep.de/twinlife/data/za6701_person_v3-0-0/edu0203

**Comment by afuetterer** [comment]
Was genau ist hier das Problem? Die Variable hat sich seit dem Update im Mai nicht geändert.
Ist es korrekt, dass die Labels / Values 1, 3, 4 ohne Beschriftung sind?
Es geht "nur" um die Sortierung, richtig?

Also 12, 20, 12.5, 3.8 -> 3.8, 5, 12.5, 20.
Korrekt?

**Comment by kkrell** [comment]
Ja es geht nur um die Sortierung (die so sein sollte wie von dir beschrieben). Evtl. war die schon beim letzten Testupdate falsch und war uns nur nicht aufgefallen.
Dass die Werte keine Labels haben ist korrekt.

**Comment by afuetterer** [comment]
Die Ursache ist gefunden. Aber die Daten sind noch nicht auf dem Testserver.
Aber ich denke, so ist es richtig sortiert?

![edu0203](https://user-images.githubusercontent.com/35225576/60734241-94408580-9f4f-11e9-9f48-521e1a600da8.png)

**Comment by kkrell** [comment]
Ja, ist es! Danke.
