### ISSUE TITLE
Conceptual, Period, Analysis Unit

### ISSUE THREAD

**Issue by volkerlang** [paneldata/twinlife#32]
Bei datasets.csv ist conceptual nicht befüllt, bei instruments.csv ist period und analysis_unit nicht befüllt

![reihenfolgezahlen](https://cloud.githubusercontent.com/assets/15111430/20842581/4b541fd8-b8b8-11e6-87af-6c9f2dbb2fe7.JPG)

**Comment by volkerlang** [comment]
Falsches Bild, jetzt das richtige - sorry:
![datasetsinstruments](https://cloud.githubusercontent.com/assets/15111430/20842619/682855de-b8b8-11e6-94c7-41fb9da91f12.JPG)

**Comment by mhebing** [comment]
Ok, dass mit period und analysis_unit bei den instruments dauert leider noch mal kurz…

**Comment by kkrell** [comment]
Hat sich erledigt.

**Comment by volkerlang** [comment]
Hat sich erledigt (sh. oben) :-)
