### ISSUE TITLE
Update metadata to "v3-0-0"

### ISSUE THREAD

**Issue by afuetterer** [paneldata/twinlife#40]
Proposed workflow:

* [x] clean up
    * [x] delete stale branch "twinlife-v2-1-0-isieber"
    * [x] delete outdated xml files in r2ddi/*
    * [x] delete outdate json files in [ddionrails/datasets](https://github.com/paneldata/twinlife/tree/master/ddionrails/datasets), see https://github.com/paneldata/twinlife/pull/39#issuecomment-491251129
    * [x] update fill_ddionrails.py
    * [x] add Pipfile
    * [x] remove unnecessary files in lib_py/
* [x] create branch "v3-0-0"
* [x] merge PR in branch "v3-0-0"
* [x] gather recent versions of all required metadata files, *.csv
    * [x] answers.csv
    * [x] datasets.csv
    * [x] logical_variables.csv, see https://github.com/paneldata/twinlife/issues/41
    * [x] questionnaires.csv
    * [x] questions.csv
    * [x] study.md
* [x] prepare additional *.csv files, see https://github.com/paneldata/twinlife/pull/43
    * [x] analysis_units.csv
    * [x] periods.csv
    * [x] conceptual_datasets.csv
* [x] generate *.xml files
    * [x] validate "missing = True" is generated correctly
* [x] generate *.json files
* [x] generate preprocessed *.csv files
* [x] create PR from branch "v3-0-0" into master
* [x] import everything to test server
* [ ] validate that everything works as expected
* [ ] review issues:
  * [x] https://github.com/paneldata/twinlife/issues/13
  * [x] https://github.com/paneldata/twinlife/issues/18
  * [x] https://github.com/paneldata/twinlife/issues/31
  * [x] https://github.com/paneldata/twinlife/issues/49
* [ ] merge branch "v3-0-0" into master
* [ ] create "v3-0-0" tag
* [ ] import everything to production server, i.e. paneldata.org

**Comment by afuetterer** [comment]
- [x] @volkerlang : Die Datei "logical_variables.csv" ist ebenfalls nicht valide. Da ist auch noch ein Diff-Rest drin. Kannst du bitte eine neue Version pushen?

**Comment by afuetterer** [comment]
- [x] @volkerlang : Die Spalte "conceptual_name" in `datasets.csv` sollte "conceptual_dataset_name" heißen.

**Comment by volkerlang** [comment]
@afuetterer: Sorry, dass mir die Diff nicht aufgefallen war. Ist removed. Die Spalte hab ich auch umbenannt.

Viele Grüße,
Volker

**Comment by kkrell** [comment]
Hallo Alex, kurze Rückfrage: Arbeiten wir jetzt aktuell noch am v3-0-0 Branch, oder hast du den schon in den Master gemergt? Ich hab gerade ein wenig den Überblick verloren.

Ich teste gerade die Updates und mir sind schon ein paar Dinge aufgefallen. Ich öffne dann wieder entsprechende Issues.
