### ISSUE TITLE
Provide valid "logical_variables.csv" file

### ISSUE THREAD

**Issue by afuetterer** [paneldata/twinlife#41]
Die Datei `logical_variables.csv` aus dem letzten Pull Request https://github.com/paneldata/twinlife/pull/39 war nicht valide.

**Comment by volkerlang** [comment]
Müsste jetzt passen!

Viele Grüße, 
Volker

**Comment by afuetterer** [comment]
see e58125ffd207b7ff51335e4ffe402373664035aa
