### ISSUE TITLE
Anzeige Variablen nach Wellen

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#50]
Sind grundsätzlich folgende Dinge möglich:

- Ausgabe der Häufigkeiten einer Variable nach WELLEN (wir haben ja ein Long-Format, sprich eine Variable über alle Wellen), wobei die Variable "wid" (wave ID) angibt, zu welcher Welle eine Beobachtung gehört. 

- Anzeige, in welchen Wellen eine Variable erhoben wurde. Quasi eine Auflistung z.B. unter dem Häufigkeitsdiagramm der Variable: F2F1, CATI1, [F2F2], ... wenn die Variable jedes Jahr erhoben wurde, aber auch F2F1, F2F2 usw. wenn sie zwischendurch in CATI1 nicht erhoben wurde.

**Comment by afuetterer** [comment]
@kkrell : Bitte nenn ein konkretes Beispiel. Welche Variable ist ein "Kandidat" für diese Anzeige.

@kwenzig @jgoebel : Ist das mit SOEP-Long vergleichbar? Da werden die Grafiken ja demnächst per Bild eingebunden.

Könnt ihr die zwei Fragen beantworten?

**Comment by kkrell** [comment]
Beispiel wäre die Variable gls0100. Die wurde in beiden Wellen (F2F1 und CATI1) erhoben. Wenn eine Darstellung der Häufigkeiten getrennt nach Wellen (Wellenindikator ist die Variable _wid_) möglich wäre, wäre das phantastisch.

Und ich glaube, unsere Datensatzstruktur ist vergleichbar mit SOEP-long.

**Comment by afuetterer** [comment]
Das wäre phantastisch. Das finden die SOEP-Long-Macher auch. Das ist zur Zeit aber nicht möglich.
Ich würde sagen, dass das ein Issue für die Software ist und nicht in dieses Repository gehört.
Können wir es hier schließen?

**Comment by kkrell** [comment]
Jepp, danke für das Statement.

**Comment by kkrell** [comment]
Sorry, ich muss noch mal öffnen, meine zweite Frage war ja noch nicht beantwortet:

- Anzeige, in welchen Wellen eine Variable erhoben wurde. Quasi eine Auflistung z.B. unter dem Häufigkeitsdiagramm der Variable: F2F1, CATI1, [F2F2], ... wenn die Variable jedes Jahr erhoben wurde, aber auch F2F1, F2F2 usw. wenn sie zwischendurch in CATI1 nicht erhoben wurde.

Diese Info pro Variable prominent zu platzieren wäre schon hilfreich.

**Comment by afuetterer** [comment]
Dieser Issue betrifft das System und nicht die TwinLife-Metadaten.
Ich habe diesen Issue geöffnet: ddionrails/ddionrails#731
