### ISSUE TITLE
Related variables bei Fragebatterien werden nicht immer angezeigt (z.B. gls0100)

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#51]
gls0100 ist bei uns eine Fragebatterie zum Thema Zufriedenheit. Im CATI-Fragebogen werden korrekterweise in der rechten Spalte die zu der Batterie gehörigen Variablen angezeigt, im "Hauptfeld" wird die Matrix dargestellt.
Bei allen F2F1-Fragebögen (die Frage kommt dort in mehreren Fragebögen vor) wird auch die Matrix im Hauptfeld angezeigt, rechts fehlen jedoch die related variables.

Bei einer anderen Variable, wo ich das überprüft habe (aas0100t) funktioniert es auch. Habe jetzt nur bei gls0100 den Fehler entdeckt (bisher).

**Comment by afuetterer** [comment]
- Was ist eine Fragenbatterie?
- Ist gls0100 eine Variable oder eine Frage oder weder noch?
- Wo genau liegt das Problem?

Bitte gib einen bzw. mehrere Links an, auf denen das Problem besteht.

**Comment by kkrell** [comment]
Eine Fragebatterie ist eine Frage, zu der mehrere Variablen gehören (in unserem Beispiel gls0100 bis gls1000). Diese werden dann in paneldata als Matrix angezeigt, siehe hier:
https://ddionrails.soep.de/twinlife/inst/twinlife-2016-cati_personenfragebogen/gls0100

gls0100 ist in unserem Fall die Frage "At the beginning I would like to know how satisfied are you with your life in general. Here are some statements to which you agree or you can refuse. Please answer on a scale of 1 to 5, where 1 is strongly disagree and 5 means strongly agree." und gleichzeitig das erste dazugehörige Item/Variable "In most ways my life is close to my ideal."
Die weiteren dazugehörigen Items (Variablen gls0200 bis gls1000) werden dann korrekterweise in der Spalte rechts als "related variables" angezeigt. Jedes Item ist also eine eigene Variable mit Häufigkeiten usw.
Im CATI-Fragebogen, den ich oben verlinkt habe, funktioniert es genau so wie es soll.

In den F2F-Fragebögen, wo diese Frage vorkommt, jedoch nicht: Hier wird die Matrix korrekt angezeigt, aber die Auflistung der "related variables" rechts fehlt:
https://ddionrails.soep.de/twinlife/inst/twinlife-2014-f2f_alteri-onlinefragebogen/gls0100
(Hier sind es nur fünf Items/Variablen, die zur Frage gehören: gls0100 bis gls0500).

**Comment by afuetterer** [comment]
Danke für die Erklärung.

Diese Verbindung zwischen Frage "gls0100" und Variable(n) erfolgt über die Datei "questions_variables.csv". So wie es aussieht hat Marcel für euch die Datei "logical_variables.csv" ein bisschen bearbeitet und in "questions_variables.csv" umbenannt.

In der Datei "questions_variables.csv" bzw "logical_variables.csv" ist "gls0100" auf der Seite der Fragen nur im Fragebogen "twinlife-2016-CATI_Personenfragebogen" angegeben.

Die gleichnamige Frage "gls0100" aus "twinlife-2014-f2f_alteri-onlinefragebogen" hat keine Variablenverbindung.

Das Verhalten des Systems ist in diesem Fall also richtig. Das Problem, wenn wir es so nennen wollen, liegt in den Daten / Metadaten.

Die Lösung liegt bei euch: Ihr müsstet die Verbindung zwischen twinlife-2014-f2f_alteri-onlinefragebogen/gls0100 und der Variable "gls0100" ergänzen.

Können wir das Issue schließen?

**Comment by kkrell** [comment]
Alles klar, ja, das Issue kann geschlossen werden. Nur eine Frage noch: Ist es denn ok wenn wir weiter die logical_variables.csv anpassen, oder machen wir die Anpassung nicht besser direkt in questions_variables.csv? Diese liegt uns jedoch im Moment gar nicht vor.

**Comment by afuetterer** [comment]
Ihr könnt die Änderungen in "logical_variables.csv" vornehmen. Die Datei "questions_variables.csv" wird (noch) hier erzeugt. Wenn die Regeln für die Metadaten stehen, könnt ihr die direkt erstellen.

**Comment by kkrell** [comment]
Kann das Issue noch mal geöffnet werden? Seit dem erneuten Update werden überhaupt keine related variables mehr bei den Fragebatterien angezeigt.

**Comment by afuetterer** [comment]
Es wurden scheinbar keine Verknüpfungen zwischen Fragen und Variablen importiert.
Ich sehe gleich nach.
https://ddionrails.soep.de/twinlife/inst/twinlife-2014-f2f_alteri-onlinefragebogen/gls0100

**Comment by afuetterer** [comment]
Die Ursache ist behoben.

**Comment by afuetterer** [comment]
<https://ddionrails.soep.de/twinlife/inst/twinlife-2014-F2F_Alteri-OnlineFragebogen/gls0100>
