### ISSUE TITLE
Neuen Datensatz unkompliziert ins System integrieren?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#52]
Wir haben noch eine Frage. Bisher dokumentieren wir nur die Daten, die direkt auf dem Erhebungsdaten basieren und mit Fragebögen verknüpfbar sind.

Wir haben noch zwei weitere Datensätze, die lediglich generierte Variablen enthalten. Wäre es möglich, diese beiden kurzfristig noch mit ins System zu integrieren, OHNE dafür questions.csv, answers.csv und logical_variables.csv anzupassen (dann gibt es halt nur die Variablenanzeige auf paneldata.org und keine Verknüpfung zu Fragebogen etc.)? Lediglich die csvs, die Bezug auf die dokumentierten Datensätze nehmen (sprich z.B. datasets.csv, bzw. wo auch immer die Datensätze sonst noch aufgelistet werden), würden wir dann anpassen.
Oder muss z.B. answers.csv auf jeden Fall angepasst werden, falls im neuen Datensatz neue Labels vorkommen?

**Comment by afuetterer** [comment]
Ihr könnt die Datensätze ohne Verknüpfungen zu Fragen liefern.
Sind die Datensätze schon Teil der Lieferung?

**Comment by kkrell** [comment]
Vielen Dank für die Info!
Nein, bisher sind die Datensätze noch nicht geliefert worden. Das machen wir dann beim nächsten Release und passen entsprechend auch die csv's an der Stelle an.
