### ISSUE TITLE
Systemissue: Anzeige der Variablennamen innerhalb einer Fragematrix

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#54]
Ich weiß, dass es eher ein System-Issue ist; vielleicht kannst du hier kurz antworten und den Issue dann schließen: 
Eine Rückfrage aus dem Team: Ist es geplant, dass innerhalb von Matrizen/Itembatterien auch bei der Matrix selbst der dazugehörige Variablenname angezeigt wird?
Beispiel: https://ddionrails.soep.de/twinlife/inst/twinlife-2014-f2f_modul4_casi/sre0100s
Dass dann vor dem Item "Most children are affectionate with their brother or sister sometimes even though they fight at other times. How often are you physically affectionate with [name of sibling] (such as by hugging, kissing, holding hands)?" in der Matrix der dazugehörige Variablenname angezeigt wird (in diesem Fall sre0101s). Bisher ist für den Nutzer der dazugehörige Variablenname nur aus der Liste rechts (related variables) ersichtlich.

**Comment by afuetterer** [comment]
@hansendx: Kannst du kurz Feedback geben und das Issue schließen?

**Comment by afuetterer** [comment]
Ich ziehe das auch zu ddionrails um:
https://github.com/ddionrails/ddionrails/issues/734

**Comment by hansendx** [comment]
Ich Antworte noch einmal hier, bevor ich dann zu ddionrails/ddionrails#734 wechsle.

So wie das Datenmodell im moment ist, ist das keine triviale Sache.
Die existieren als einzelnes Element gar nicht in der Datenbank. Deshalb koennen sie auch keine Verbindung zu einer Variable haben.
Die Frage an sich kann Verbindungen zu Variablen haben, wenn man die allerdings an die items haengt, steht dort ueberall das gleiche. 
Potentiell waere ich dem ganzen nicht abgeneigt, weil es den Nutzern des Portals mehr information vermittelt.
Allerdings habe ich das Gefuehl, dass in den items je nach Studie unterschiedliche Dinge abgebildet werden.
Wir koennen das in ddionrails/ddionrails#734 im Auge behalten, ich wuerde dann in naechster Zeit klaeren muessen was die eigentliche Intention fuer items in Fragen war.
