### ISSUE TITLE
Anzeige von Häufigkeiten bei ID-Variablen u.ä. verhinderbar?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#55]
Aktuell werden Häufigkeiten zu allen IDs angezeigt, wenn man sich eine solche Variable anzeigen lässt. (https://ddionrails.soep.de/twinlife/data/za6701_zygosity_v3-0-0/hid)
Kann man diese Ausgabe bei dieser Art Variablen irgendwie unterbinden? Also können WIR in irgendeiner csv in einer bestimmten Spalte angeben, dass für diese Variable keine Häufigkeiten angezeigt werden sollen?

Passend dazu: Bei der Variable ptyp (https://ddionrails.soep.de/twinlife/data/za6701_person_v3-0-0/ptyp) werden die Kategorien, für die es keine Fälle gibt, dennoch angezeigt, obwohl unten bei "Label table" steht: Please note that labels are simplified and values with frequency = 0 are hidden.

**Comment by afuetterer** [comment]
Dieses Issue betrifft das System und nicht die TwinLife-Metadaten.
Ich habe dieses Issue geöffnet: ddionrails/ddionrails#732
