### ISSUE TITLE
Anzeige der related variables sortiert nach "item" aus logical_variables möglich?

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#56]
Die Anzeige der Items in den Fragematrizen ist in der richtigen Reihenfolge, allerdings sind die related variables in der Spalte rechts anders (nämlich nach Variablennamen statt nach item-Nummer) sortiert. In den meisten Fällen ist das identisch, aber bei https://ddionrails.soep.de/twinlife/inst/twinlife-2014-f2f_modul4_casi/ses0100 z.B. nicht. Können die related variables auch nach der Spalte "item" in logical_variables.csv sortiert werden, damit es konsistent mit der Anzeige der Matrix ist?

**Comment by afuetterer** [comment]
Dieses Issue betrifft das System und nicht die TwinLife-Metadaten.
Ich habe dieses Issue geöffnet: ddionrails/ddionrails#733
