### ISSUE TITLE
Tabellarische Darstellung der Antworten von Items bei Fragen funktioniert nicht mehr

### ISSUE THREAD

**Issue by kkrell** [paneldata/twinlife#61]
Bei Fragen, zu denen mehrere Variablen/Items gehören, wird diese Matrix im Instrument nicht mehr angezeigt.
Zuvor stand oben die Frage und darunter die dazugehörigen Items mit der Antwortskala (und Antwortkästchen zur Darstellung der Frage).
Nun wird nur noch die übergeordnete Frage angezeigt:
https://ddionrails.soep.de/twinlife/inst/twinlife-2014-F2F_Modul5_CASI/dia0100

Die related Variables werden nun wieder korrekt in der Spalte rechts verlinkt.

**Comment by hansendx** [comment]
Durch einen Formatierer hatten sich beim Update zu Bootstrap 4, Leerzeichen in den code fuer die Erzeugung der Tabelle eingeschlichen.
Das Problem ist lokalisiert und ich werde den fix schnellstmoeglich auf [paneldata](http://paneldata.org) live stellen.
Ich schliesse das Issue hier erstmal und migriere es zum [GitHub projekt](https://github.com/ddionrails/ddionrails).

Siehe  [#816](https://github.com/ddionrails/ddionrails/issues/816)
